esphome:
  name: nobo

esp32:
  board: upesy_wroom
  framework:
    type: arduino

# Enable logging
logger:

ota:
  password: "YourPassword"

wifi:
  ssid: "YourSsid"
  password: "YourPassword"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nobo Fallback Hotspot"
    password: "3QmeXUbBbO85"

captive_portal:
    
web_server:
  port: 80

i2c:
  sda: 32
  scl: 33
  scan: False
  frequency: 50kHz

external_components:
  - source:
      type: git
      url: https://github.com/csabigee/nobo
      ref: main
    components: [ nobo ]

climate:
  - platform: nobo
    name: "Nobo Heater LivingRoom"
    nominal_power: 2000 W
    power:
      name: "Nobo Heater Power LivingRoom"
    update_interval: 30s
